name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.2'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Activate virtual environment and install dependencies
        run: |
          ls ./functions
          source ./functions/venv/Scripts/activate
          ls ./functions/venv
          pip install -r ./functions/venv/requirements.txt
      
      - name: Deploy functions to production
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          source venv/bin/activate
          firebase deploy --only functions
        

      
      - name: Set up Flutter
        uses: subosito/flutter-action@main
        with:
          flutter-version: '3.22.2'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@main
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_CREDENTIALS }}
          channelId: live
          projectId: webbcheck
        env: 
          FIREBASE_CLI_EXPERIMENTS: webframeworks


      

