name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.2'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Create and activate virtual environment and install dependencies
        run: |
          python3 -m venv ./functions/venv
          source ./functions/venv/Scripts/activate
          pip install -r ./functions/requirements.txt
      
      - name: Deploy functions to production
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Set up Flutter
        uses: subosito/flutter-action@main
        with:
          flutter-version: '3.22.2'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@main
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_CREDENTIALS }}
          channelId: live
          projectId: webbcheck
        env: 
          FIREBASE_CLI_EXPERIMENTS: webframeworks
