name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Buld and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      
      
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '18.18.2'
      
      - name: install firebase cli
        run: npm install -g firebase-tools
      
      - name: Deploy functions to production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions
        

      
      - name: Set up Flutter
        uses: subosito/flutter-action@main
        with:
          flutter-version: '3.22.2'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@main
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_CREDENTIALS }}
          channelId: live
          projectId: webbcheck
        env: 
          FIREBASE_CLI_EXPERIMENTS: webframeworks


      

