name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 
          # this error will happen if python is not set up or if the pip package relevent to the deploy is not found
          # Error: Failed to find location of Firebase Functions SDK. Did you forget to run '"C:\Users\tyler\Documents\GitHub\webbpulse_checkout\functions\venv\Scripts\activate.bat"  && python.exe -m pip install -r requirements.txt'?
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: install python dependencies
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          python -m venv ./functions/venv 
          source ./functions/venv/bin/activate
          pip install -r ./functions/requirements.txt
          deactivate
          echo "$GCP_SA_KEY" > ./gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp_key.json
          firebase deploy --only functions --debug
          

      - name: Set up Flutter
        uses: subosito/flutter-action@main
        with:
          flutter-version: '3.22.2'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@main
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_CREDENTIALS }}
          channelId: live
          projectId: webbcheck
        env: 
          FIREBASE_CLI_EXPERIMENTS: webframeworks
