name: Deploy Firebase Functions

on:
  push:
    branches:
      - firebase-functions-testing  # Trigger on push to the firebase functions testing branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 
          # this error will happen if python is not set up or if the pip package relevent to the deploy is not found
          # Error: Failed to find location of Firebase Functions SDK. Did you forget to run '"C:\Users\tyler\Documents\GitHub\webbpulse_checkout\functions\venv\Scripts\activate.bat"  && python.exe -m pip install -r requirements.txt'?
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Functions
        env:

          FIREBASE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_APPLICATION_CREDENTIALS }}
        run: |
          python -m venv ./functions/venv 
          source ./functions/venv/bin/activate
          pip install -r ./functions/requirements.txt
          deactivate
          echo "$FIREBASE_APPLICATION_CREDENTIALS" > ./functions/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=./functions/gcp_key.json
          firebase deploy --only functions --debug